helmDefaults:
  kubeContext: kind-local-kind
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
releases:
  # ingress controller
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.12.2
    values:
      - controller:
          watchIngressWithoutClass: true
          ingressClass: nginx
          ingressClassByName: false
          ingressClassResource:
            default: true
            enabled: true
#          extraArgs:
#            publish-status-address: localhost
          hostPort:
            enabled: true
          service:
            type: NodePort
            externalTrafficPolicy: Local
          nodeSelector:
            kubernetes.io/os: 'linux'
            ingress-ready: 'true'
  ## regular k8s manifests
  - name: manifests
    chart: "./manifests"